### ISSUE TITLE
Libicu 65 breaks OpenOffice?

### ISSUE THREAD

**Issue by DavidMcKenna** [bitwiseworks/icu-os2#1]
After installing libicu version 65, I can no longer open an OpenOffice text document, the icon stays hatched for a moment, then un-hatches. Popuplog shows:

04-25-2020  08:51:44  SYS2070  PID 004b  TID 0001  Slot 004f
C:\PROGRAMS\OPENOFFICE4\PROGRAM\SOFFICE.BIN
I18NPOOL->ICUUC.__ZN3icu13UnicodeStringC1EPKw
127

 Also, if I try to open the OpenOffice 'Base' object, popuplog shows:

04-25-2020  08:56:07  SYS2070  PID 005c  TID 0001  Slot 0090
C:\PROGRAMS\OPENOFFICE4\PROGRAM\SOFFICE.BIN
I18NPOOL->ICUUC.__ZN3icu22RuleBasedBreakIterator5resetEv
127

 Spreadsheets seem to work OK. Reverting to libicu version 56 corrects these errors.

**Comment by DavidMcKenna** [comment]
OpenOffice version 4.1.7.

**Comment by SilvanScherrer** [comment]
Just a short question. Did you reboot after the icu update?

**Comment by DavidMcKenna** [comment]
Yes, I upgraded and downgraded twice, rebooting each time. Both times with version 65 I got this result.

**Comment by SilvanScherrer** [comment]
Ok thx for testing. We can reproduce it. but it smells like a old Apache OpenOffice bug. As the failing api should not be used at all, as it was clearly marked as private in the older sources. Anyway stay tuned for an update on aoo

**Comment by abwillis** [comment]
Any update on this?

**Comment by SilvanScherrer** [comment]
next AOO fixes it

**Comment by SilvanScherrer** [comment]
just to let you know, upcoming AOO 4.1.8 release fixes this. But users not using AOO 4.1.8 should never upgrade to latest ICU, as it breaks old AOO. But in the end users not upgrading to AOO 4.1.8 will never be able to use new QT5 based browser, as it need the new ICU as well.
We are sorry to break compatibility, but it's AOO fault and not ICU.
