### ISSUE TITLE
Dose AOO support build on aarch64?

### ISSUE THREAD

**Issue by Liu-Richard** [bitwiseworks/icu-os2#2]
**Is your feature request related to a problem? Please describe.**
I want to build AOO-415 on arm server, but it has a lot of issue as follow 

[root@yum-source main]# ./bootstrap.1

chmod: cannot access ‘/solenv/bin/build.pl’: No such file or directory
chmod: cannot access ‘/solenv/bin/build_client.pl’: No such file or directory
chmod: cannot access ‘/solenv/bin/zipdep.pl’: No such file or directory
chmod: cannot access ‘/solenv/bin/gccinstlib.pl’: No such file or directory

**Describe the solution you'd like**
support arm server to build and install

**Describe alternatives you've considered**

**Additional context**

**Comment by SilvanScherrer** [comment]
This is the wrong project you reported the issue. I suggest you to ask at AOO bugtracker.
